### ISSUE TITLE
Tasks for Converting Old Tracking to New

### ISSUE THREAD

**Issue by zarathustra323** [cygnusb2b/fortnight-graph#78]
Once the `0.2.0` library has been deployed and tested, remove the following tracking elements from the the backend:

- [x] Traces of the `{{{ beacon }}}` variable from templates
- [x] Drop the `/e/:token/:event.gif` route and redirect (?) traffic
- [x] Drop the `/t/` routes entirely. Resolved by #90 
- [x] Redirect the `/go/` routes to `/redir/`. Resolved by #90
- [x] No longer verify tokens in the `/redir/` routes and stop tracking clicks; deprecate the route. Resolved by #90
- [x] Update the `campaign/delivery` repository and no longer use URL/token redirects. Resolved by #90
- [x] Completely drop the` campaign/placement` repo. Resolved by #90
- [ ] Determine which events to pre-aggregate, and at what time intervals
- [x] Stop directly storing requests. Resolved by #81 
- [ ] Update the tracking to support redirects _for campaigns only_; for legit bot tracking
- [x] **Add the FortnightJS tracking for templates without fallbacks** per #88. Resolved by #90.
- [x] Gzip image responses and/or determine how to make the response size smaller
